apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: imagepullsecret-patcher
  name: imagepullsecret-patcher
  namespace: imagepullsecret-patcher
spec:
  replicas: 1
  selector:
    matchLabels:
      name: imagepullsecret-patcher
  template:
    metadata:
      labels:
        name: imagepullsecret-patcher
    spec:
      automountServiceAccountToken: true
      containers:
        - env:
            - name: CONFIG_FORCE
              value: "true"
            - name: CONFIG_EXCLUDED_NAMESPACES
              value: kube-node-lease,kube-public,kube-system,monitoring
            - name: CONFIG_DEBUG
              value: "false"
            - name: CONFIG_ALLSERVICEACCOUNT
              value: "true"
            - name: CONFIG_DOCKERCONFIGJSONPATH
              value: /app/secrets/.dockerconfigjson
          image: quay.io/titansoft/imagepullsecret-patcher:v0.14
          name: imagepullsecret-patcher
          resources:
            limits:
              cpu: 0.2
              memory: 30Mi
            requests:
              cpu: 0.1
              memory: 15Mi
          volumeMounts:
            - mountPath: /app/secrets
              name: src-dockerconfigjson
              readOnly: true
      serviceAccountName: imagepullsecret-patcher
      volumes:
        - name: src-dockerconfigjson
          secret:
            secretName: image-pull-secret-src
