appName: metrics-server
userGivenName: metrics-server
destNamespace: metrics-server
destServer: https://kubernetes.default.svc
srcPath: ''
repoURL: https://kubernetes-sigs.github.io/metrics-server/
srcRepoURL: https://kubernetes-sigs.github.io/metrics-server/
targetRevision: '3.8.1'
labels:
exclude: ''
include: ''
helm:
  chart: metrics-server
  valueFiles: values