appName: guestbook-helm
userGivenName: guestbook-helm
destNamespace: default
destServer: https://kubernetes.default.svc
srcPath: helm-guestbook
repoURL: https://github.com/argoproj/argocd-example-apps.git
srcRepoURL: https://github.com/argoproj/argocd-example-apps.git
targetRevision: master
labels:
exclude: ''
include: ''
helm:
  valueFiles: values