appName: echo-test-2
userGivenName: echo-test-2
destNamespace: default
destServer: https://kubernetes.default.svc
srcPath: internals/cicd/helm/echo-test-2/
repoURL: git@bitbucket.org:mercury_cash/echo-test-2.git
srcRepoURL: git@bitbucket.org:mercury_cash/echo-test-2.git
srcTargetRevision: master
labels:
exclude: ''
include: ''
helm:
  valueFiles: values-prod